.gitignore, riposte-spi/src/main/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListener.java, riposte-spi/src/main/java/com/nike/riposte/server/error/exception/Forbidden403Exception.java, riposte-spi/src/test/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListenerTest.java, riposte-spi/src/test/java/com/nike/riposte/server/error/exception/Forbidden403ExceptionTest.java
This simple change allows 403 responses to be returned similar to the other 4xx HTTP responses.
=> Add support for 403 responses

riposte-spi/src/main/java/com/nike/riposte/server/http/RequestInfo.java, riposte-spi/src/main/java/com/nike/riposte/server/http/impl/RequestInfoImpl.java, riposte-spi/src/test/java/com/nike/riposte/server/http/impl/RequestInfoImplTest.java
This PR fills the gap identified in issue #11 .
Decode the value before setting the path inside RequestInfoImpl.
After this is merged, when you call requestInfo.getPathParam("blah") it will be the decoded value where previously it was the raw, encoded value
=> Issue 11 - Decode path before setting in RequestInfoImpl

riposte-core/src/main/java/com/nike/riposte/server/channelpipeline/HttpChannelInitializer.java, riposte-core/src/test/java/com/nike/riposte/server/channelpipeline/HttpChannelInitializerTest.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyBeforeAndAfterSecurityRequestAndResponseFiltersComponentTest.java, riposte-spi/src/main/java/com/nike/riposte/server/http/filter/RequestAndResponseFilter.java, riposte-spi/src/test/java/com/nike/riposte/server/http/filter/RequestAndResponseFilterTest.java
This PR implements the functionality described in issue #15 .
Allow a RequestFilter to specify to be ran before or after SecurityValidationHandler
=> Issue15 - Allow Request Filters to be ran before or after SecurityValidationHandler

riposte-core/src/main/java/com/nike/riposte/server/channelpipeline/HttpChannelInitializer.java, riposte-core/src/main/java/com/nike/riposte/server/handler/RequestInfoSetterHandler.java, riposte-core/src/main/java/com/nike/riposte/server/http/ProxyRouterEndpoint.java, riposte-core/src/test/java/com/nike/riposte/server/channelpipeline/HttpChannelInitializerTest.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyRequestSizeValidationComponentTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/RequestInfoSetterHandlerTest.java, riposte-spi/src/main/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListener.java, riposte-spi/src/main/java/com/nike/riposte/server/config/ServerConfig.java, riposte-spi/src/main/java/com/nike/riposte/server/http/Endpoint.java, riposte-spi/src/main/java/com/nike/riposte/server/http/RequestInfo.java, riposte-spi/src/main/java/com/nike/riposte/server/http/impl/RequestInfoImpl.java, riposte-spi/src/test/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListenerTest.java, riposte-spi/src/test/java/com/nike/riposte/server/config/ServerConfigTest.java, riposte-spi/src/test/java/com/nike/riposte/server/http/RequestInfoTest.java
issue #27 
This PR will add the functionality of validating each request against a globally configured request size.
By default, endpoints do not override and will default to the global.
You can override the global configuration inside each endpoint.
ProxyRouterEndpoints have this validation disabled by default
=> Validate request size against global or endpoint provided max request size

riposte-core/src/main/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClient.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyProxyRequestsDoNotAlterRequestToDownstreamServiceTest.java
This PR addresses Issue #29 
Allow clients to set a Content-Length header and proxy those through but still support chunked when the client sets it
=> Remove Forced Chunked Transfer-Encoding for Proxy Endpoints

.codecov.yml, riposte-core/src/main/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClient.java, riposte-core/src/main/java/com/nike/riposte/server/handler/ChannelPipelineFinalizerHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/ExceptionHandlingHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/IdleChannelTimeoutHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/IncompleteHttpCallTimeoutHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/NonblockingEndpointExecutionHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/ProxyRouterEndpointExecutionHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/RequestFilterHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/RequestInfoSetterHandler.java, riposte-core/src/main/java/com/nike/riposte/server/http/ProxyRouterProcessingState.java, riposte-core/src/main/java/com/nike/riposte/util/AsyncNettyHelper.java, riposte-core/src/test/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClientTest.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyResponseHttpStatusCodeHandlingRfcCorrectnessComponentTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/ChannelPipelineFinalizerHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/ExceptionHandlingHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/IncompleteHttpCallTimeoutHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/NonblockingEndpointExecutionHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/RequestFilterHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/RequestInfoSetterHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/util/AsyncNettyHelperTest.java, riposte-metrics-codahale/src/main/java/com/nike/riposte/metrics/codahale/CodahaleMetricsListener.java, riposte-spi/src/main/java/com/nike/riposte/server/http/impl/RequestInfoImpl.java, riposte-spi/src/main/java/com/nike/riposte/server/http/impl/RiposteInternalRequestInfo.java, riposte-spi/src/test/java/com/nike/riposte/server/http/impl/RequestInfoImplTest.java
This should fix the following:
* No more Netty ByteBuf reference counting memory leaks. If you saw any log messages that looked like `LEAK: ByteBuf.release() was not called before it's garbage-collected` then this should fix that. 
* No more (rare) race conditions when processing `ProxyRouterEndpoint` requests that could lead to requests not being handled correctly.
* Better internal corner-case error handling for `ProxyRouterEndpoint` requests, leading to less log spam warnings.
* Improved logging when corner case errors do pop up. If a request is handled in an unexpected way and you have the trace ID from the response headers, then the logs should give you better insight into what happened (i.e. caller or downstream system dropping connection partway through a request).
=> Fix ByteBuf memory leaks, race conditions, corner case error handling

riposte-core/src/main/java/com/nike/riposte/server/handler/NonblockingEndpointExecutionHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/ProxyRouterEndpointExecutionHandler.java, riposte-core/src/test/java/com/nike/riposte/server/handler/NonblockingEndpointExecutionHandlerTest.java
=> Replace OneTimeTask references with lambdas

riposte-spi/src/main/java/com/nike/riposte/server/http/RequestInfo.java, riposte-spi/src/main/java/com/nike/riposte/server/http/impl/RequestInfoImpl.java, riposte-spi/src/test/java/com/nike/riposte/server/http/RequestInfoTest.java, riposte-spi/src/test/java/com/nike/riposte/server/http/impl/RequestInfoImplTest.java
Per issue #55 , The purpose of this PR is to add a method to get the path template from the request. 
Add a new method, getPathTemplate, to the RequestInfo interface and implementation.
=> Add getPathTemplate method to RequestInfo

riposte-core/src/main/java/com/nike/riposte/server/channelpipeline/HttpChannelInitializer.java, riposte-core/src/main/java/com/nike/riposte/server/handler/RequestInfoSetterHandler.java, riposte-core/src/main/java/com/nike/riposte/server/handler/RoutingHandler.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyRequestSizeValidationComponentTest.java, riposte-core/src/test/java/com/nike/riposte/server/handler/RoutingHandlerTest.java, riposte-spi/src/main/java/com/nike/riposte/util/HttpUtils.java
Per #37 , Configured validation in RoutingHandler to fail fast if the content-length header is set and greater than the configured max request size once we know the endpoint for the request
This was put into the RoutingHandler instead of RequestInfoSetterHandler as we do not know the endpoint yet until after the RoutingHandler figures it out, which is necessary to process an endpoint's override of the global limit.
I also refactored a couple of the requestSize methods into HttpUtils to enable both handlers to share the code of determining the max size and if it is disabled.
=> FailFast if Content-Length header value is greater than configured max request size

riposte-async-http-client/src/main/java/com/nike/riposte/client/asynchttp/ning/RequestBuilderWrapper.java, riposte-async-http-client/src/test/java/com/nike/riposte/client/asynchttp/ning/RequestBuilderWrapperTest.java
See #56 for the background.
I have two commits here per my initial analysis and suggestions in #56 . Based on feedback I can keep them both, remove one, or change the PR to a more optimal solution.
edit - removed the one commit i didn't like after discussion in the issue and updated the doc for the set url method
=> Provide Method to update the URL in a RequestBuilderWrapper and maintain modifications to the BoundRequestBuilder

riposte-core/src/main/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClient.java, riposte-core/src/test/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClientTest.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyProxyRequestsDoNotAlterRequestToDownstreamServiceTest.java
When streaming requests for proxyRouterEndpoints the host header value was never including the port in the value.
This PR will change that and the Host header will now contain the port when the port is not a default value
=> ProxyRouting downstream Host header should include the port when port is not the default value

riposte-async-http-client/src/main/java/com/nike/riposte/client/asynchttp/ning/AsyncHttpClientHelper.java, riposte-async-http-client/src/test/java/com/nike/riposte/client/asynchttp/ning/AsyncHttpClientHelperTest.java
add fluent style setters for a default signature calculator and performSubSpanAroundDownstreamCalls
=> Allow setting a default SignatureCalculator through AsyncHttpClientHelper

riposte-core/src/main/java/com/nike/riposte/util/AsyncNettyHelper.java, riposte-core/src/test/java/com/nike/riposte/server/testutils/TestUtil.java, riposte-core/src/test/java/com/nike/riposte/util/AsyncNettyHelperTest.java
Adding utility methods to AsyncNettyHelper to enable easily creating CompletableFuture using the tracing helpers.
=> Add CompletableFuture Helpers to AsyncNettyhelper

build.gradle, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyResponseHttpStatusCodeHandlingRfcCorrectnessComponentTest.java
- Upgrading to Netty 4.0.52.Final
- Fixing test: 1xx and 204 should never return content-length HTTP header
Note: these changes need full integration testing before merging to master
=> Upgrading to Netty 4.0.52.Final

riposte-core/src/main/java/com/nike/riposte/server/http/ResponseSender.java, riposte-core/src/test/java/com/nike/riposte/server/http/ResponseSenderTest.java
Pass cookie from responseInfo to actual responseObject instead of creating a new cookie with just name/value from the responseInfo cookies.
the existing flow would drop any additional properties of the cookie that was set by the endpoints. Example HttpOnly flag or max age
=> Update setting of cookies on response to allow more than name/value

riposte-core/src/main/java/com/nike/riposte/server/handler/RequestContentValidationHandler.java, riposte-core/src/main/java/com/nike/riposte/server/http/ProxyRouterEndpoint.java, riposte-core/src/test/java/com/nike/riposte/server/handler/RequestContentValidationHandlerTest.java, riposte-core/src/test/java/com/nike/riposte/server/http/ProxyRouterEndpointTest.java, riposte-spi/src/main/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListener.java, riposte-spi/src/main/java/com/nike/riposte/server/error/exception/MissingRequiredContentException.java, riposte-spi/src/main/java/com/nike/riposte/server/http/Endpoint.java, riposte-spi/src/test/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListenerTest.java, riposte-spi/src/test/java/com/nike/riposte/server/error/exception/MissingRequiredContentExceptionTest.java, riposte-spi/src/test/java/com/nike/riposte/server/http/EndpointTest.java
Per #81  add ability for an endpoint to require request content and throw an exception when not present.
=> Enable Endpoints to require request content

riposte-core/src/test/java/com/nike/riposte/server/componenttest/ServerAsynchronousProcessingComponentTest.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyPayloadHandlingComponentTest.java, riposte-spi/src/main/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListener.java, riposte-spi/src/main/java/com/nike/riposte/server/http/impl/RequestInfoImpl.java, riposte-spi/src/test/java/com/nike/backstopper/handler/riposte/listener/impl/BackstopperRiposteFrameworkErrorHandlerListenerTest.java
Also added some extra exception message and cause details to riposte-backstopper framework listener for various exceptions
=> Add support for raw byte array as a request input type

riposte-core/src/main/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClient.java, riposte-core/src/main/java/com/nike/riposte/server/handler/ProxyRouterEndpointExecutionHandler.java, riposte-core/src/main/java/com/nike/riposte/server/http/ProxyRouterEndpoint.java, riposte-core/src/test/java/com/nike/riposte/client/asynchttp/netty/StreamingAsyncHttpClientTest.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyProxyRouterTracingBehaviorComponentTest.java, riposte-core/src/test/java/com/nike/riposte/server/http/ProxyRouterEndpointTest.java, riposte-core/src/test/java/com/nike/riposte/server/testutils/ComponentTestUtils.java
Currently all proxy endpoints create a subspan around the downstream call and propagate all trace headers by default on every request
This PR adds the following two abilities
* allows an endpoint to configure a request to turn off trace header propagation 
* allows an endpoint to configure a request to not create a subspan around the downstream call
Default for these features is existing behavior, so this is a backwards compatible enhancement
=> Allow proxy endpoints to disable sub spans around downstream calls and trace header propagation

riposte-typesafe-config/src/main/java/com/nike/riposte/typesafeconfig/TypesafeConfigServer.java, riposte-typesafe-config/src/test/java/com/nike/riposte/typesafeconfig/TypesafeConfigServerTest.java
allow the appid and environment to be overriden when loading the typesafe config files
=> multiregion config files

riposte-core/src/main/java/com/nike/riposte/util/ErrorContractSerializerHelper.java, riposte-core/src/test/java/com/nike/riposte/server/componenttest/VerifyErrorResponsePayloadHandlingComponentTest.java, riposte-spi/src/test/java/com/nike/riposte/server/config/ServerConfigTest.java
=> errorResponseBodySerializer handles strings properly

riposte-spi/src/main/java/com/nike/riposte/util/MatcherUtil.java, riposte-spi/src/test/java/com/nike/riposte/util/MatcherUtilTest.java
This mainly affects the span name for the overall request if you have an endpoint listening on the '/' root path.
=> Don't strip the slash for matcher name when the path is the root path

samples/sample-2-kotlin-todoservice/build.gradle, samples/sample-2-kotlin-todoservice/src/test/kotlin/com/nike/todoservice/TodoEndpointTest.kt
- Upgrade to Gradle 4.10.2
- Upgrade to RestAssured 3.2.0
- Upgrade to Jacoco 0.8.2
- sample-2-kotlin-todoservice:
- Upgrade Kotlin version to 1.2.70
- Replace @BeforeClass/@AfterClass annotations with interceptor
because annotated methods didn't run under OpenJDK 11
Fixes #109. Build and unit tests work on both Java 8 and Java 11
=> Build on Java 11
